/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoHandleRouteImport } from './routes/producto.$handle'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoHandleRoute = ProductoHandleRouteImport.update({
  id: '/producto/$handle',
  path: '/producto/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/gracias': typeof GraciasRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/producto/$handle': typeof ProductoHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/gracias': typeof GraciasRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/producto/$handle': typeof ProductoHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/gracias': typeof GraciasRoute
  '/historia': typeof HistoriaRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/producto/$handle': typeof ProductoHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/gracias'
    | '/historia'
    | '/tienda'
    | '/api/chat'
    | '/producto/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/gracias'
    | '/historia'
    | '/tienda'
    | '/api/chat'
    | '/producto/$handle'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/gracias'
    | '/historia'
    | '/tienda'
    | '/api/chat'
    | '/producto/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  GraciasRoute: typeof GraciasRoute
  HistoriaRoute: typeof HistoriaRoute
  TiendaRoute: typeof TiendaRoute
  ApiChatRoute: typeof ApiChatRoute
  ProductoHandleRoute: typeof ProductoHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$handle': {
      id: '/producto/$handle'
      path: '/producto/$handle'
      fullPath: '/producto/$handle'
      preLoaderRoute: typeof ProductoHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  GraciasRoute: GraciasRoute,
  HistoriaRoute: HistoriaRoute,
  TiendaRoute: TiendaRoute,
  ApiChatRoute: ApiChatRoute,
  ProductoHandleRoute: ProductoHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
